"""empty message

Revision ID: 0ef178596572
Revises: 
Create Date: 2022-09-22 00:23:25.435140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef178596572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Autor',
    sa.Column('id_autor', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_autor')
    )
    op.create_table('Book',
    sa.Column('id_book', sa.BigInteger(), nullable=False),
    sa.Column('livro', sa.String(length=255), nullable=True),
    sa.Column('autor_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['Autor.id_autor'], ),
    sa.PrimaryKeyConstraint('id_book')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Book')
    op.drop_table('Autor')
    # ### end Alembic commands ###
