"""empty message

Revision ID: 6bffa824fa93
Revises: 
Create Date: 2022-09-01 01:37:41.332314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bffa824fa93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Autor',
    sa.Column('id_autor', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_autor')
    )
    op.create_table('Book',
    sa.Column('id_book', sa.BigInteger(), nullable=False),
    sa.Column('livro', sa.String(length=255), nullable=True),
    sa.Column('autor', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['autor'], ['Autor.id_autor'], ),
    sa.PrimaryKeyConstraint('id_book')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Book')
    op.drop_table('Autor')
    # ### end Alembic commands ###
