"""empty message

Revision ID: 7b6decbf79cd
Revises: 6bffa824fa93
Create Date: 2022-09-01 04:37:54.459014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b6decbf79cd'
down_revision = '6bffa824fa93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Book', sa.Column('autor_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('Book_ibfk_1', 'Book', type_='foreignkey')
    op.create_foreign_key(None, 'Book', 'Autor', ['autor_id'], ['id_autor'])
    op.drop_column('Book', 'autor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Book', sa.Column('autor', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Book', type_='foreignkey')
    op.create_foreign_key('Book_ibfk_1', 'Book', 'Autor', ['autor'], ['id_autor'])
    op.drop_column('Book', 'autor_id')
    # ### end Alembic commands ###
